from datetime import datetime
from sqlalchemy import Column, Integer, String, Text, Float, DateTime, ForeignKey
from backend.database import Base

class NewsArticle(Base):
    __tablename__ = "news_articles"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    title = Column(String, nullable=False, index=True)
    description = Column(Text, nullable=True)
    content = Column(Text, nullable=True)
    url = Column(String, unique=True, nullable=False, index=True)
    image_url = Column(String, nullable=True)
    source_name = Column(String, nullable=True, index=True)
    published_at = Column(DateTime, default=datetime.utcnow, index=True)
    category = Column(String, default="Geral", index=True)
    
    # AI Reliability analysis
    reliability_score = Column(Float, default=50.0)  # 0.0 to 100.0%
    reliability_label = Column(String, default="Duvidoso")  # Confiável, Duvidoso, Provável Fake
    
    # Reddit-style voting
    upvotes = Column(Integer, default=0)
    downvotes = Column(Integer, default=0)
    
    created_at = Column(DateTime, default=datetime.utcnow)

    @property
    def vote_balance(self):
        return self.upvotes - self.downvotes


class UserVote(Base):
    __tablename__ = "user_votes"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    article_id = Column(Integer, ForeignKey("news_articles.id"), nullable=False, index=True)
    client_id = Column(String, nullable=False, index=True)  # client UUID generated by frontend
    vote_type = Column(Integer, nullable=False)  # 1 for upvote, -1 for downvote
    created_at = Column(DateTime, default=datetime.utcnow)

